config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :trackers
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'page/about'
  get 'page/help'
  root 'page#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :tracker
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  belongs_to :user
  has_many :points

  validates :name,    presence: true,
                      length: {maximum: 35}
  validates :simple,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trackers
  has_one_attached :avatar
  before_save(:email.downcase)

  validates :name,      presence: true,
                        length: {maximum: 35}
  validates :email,     presence: true,
                        length: {maximum: 255},
                        format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                        uniqueness: {case_sensitive: false}
  validates :password,  length: {in: 8..255}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    if logged?
      @tracker_new = current_user.trackers.new
    end
  end

  def about
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Welcome back #{current_user.name}"
      redirect_to root_path
    else
      flash.now[:danger] = "Wrong email and/or password"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def show
    @tracker = Tracker.find(params[:id])
  end

  def create
    if logged?
      @tracker = current_user.trackers.new
      @tracker.name = params[:tracker][:name]
      if params[:tracker][:simple] == "1"
        @tracker.simple = 1
      else
        @tracker.simple = 0
      end
      @tracker.chart_type = params[:tracker][:chart_type]
      @tracker.color = params[:tracker][:color]
      if @tracker.save
        redirect_to @tracker
      else
        redirect_to root_url
      end
    end
  end

  def destroy
    if logged? && current_user.id = Tracker.find(params[:id]).user_id
      Tracker.find(params[:id]).destroy
    end
    redirect_back fallback_location: root_url
  end

  def update
    @tracker = Tracker.find(params[:id])
    if logged? && current_user.id == @tracker.user_id
      if @tracker.simple == 0
        if params[:t][:date] && params[:t][:points]
          dat = params[:t][:date].to_date
          val = params[:t][:points]
          if p = @tracker.points.find_by(created_at: dat.beginning_of_day..dat.end_of_day)
            p.update(value: val)
          else
            if dat < Date.current.end_of_day
              @tracker.points.create(value: val, created_at: dat)
            else
              flash.now[:danger] = "You can't commit future dates"
            end
          end
        end
      else
        if params[:date]
          dat = params[:date].to_date
          if t = @tracker.points.find_by(created_at: dat)
            t.destroy
          else
            @tracker.points.create(created_at: dat, value: 1)
          end
        end
      end
    end
    render 'show'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    if logged? && current_user == @user
      @tracker_new = current_user.trackers.new
    end
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have succesly created account"
      log_in @user
      redirect_to root_url
    else
      flash.now[:danger] = "You have an error in your sign form"
      render 'new'
    end
  end

  def destroy
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if name = params[:user][:name]
      @user.name = name
    elsif avatar = params[:user][:avatar]
      @user.avatar = avatar
    end
    @user.password = params[:user][:password]
    @user.save
    redirect_to user_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged?
    !current_user.nil?
  end
end

app/helpers/tracker_helper.rb
module TrackerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThingTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="section">
      <div id="menus-switch">
        <div></div>
      </div>
    </div>
    <div id="menus">
      <div class="section" style="background: none;">
        <div id="menus-exit"><div></div></div>
        <div class="menuitem"><%= link_to "Home", root_path %></div>
        <div class="menuitem"><%= link_to "Help", 'page/help' %></div>
        <div class="menuitem"><%= link_to "About", 'page/about' %></div>
        <% unless logged? %>
          <div class="menuitem"><%= link_to "Login", login_path %></div>
          <div class="menuitem"><%= link_to "Register", new_user_path %></div>
        <% end %>
        <div class="menuitem"><%= link_to "All users", users_path %></div>
        <% if logged? %>
          <div class="menuitem"><%= link_to "Profile", current_user %></div>
          <div class="menuitem"><%= link_to "Logout", logout_path, method: :delete %></div>
        <% end %>
      </div>
    </div>
    <div class="section">
      <% flash.each do |message_type, message| %>
        <div class="flash <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/page/about.html.erb
<h1>About this site</h1>
<p>This site was created as a learning project by Marcin Stefaniak.</p>
<p>Built on Ruby(v.2.6.0) on Rails(v.5.2.2)</p>
<p>Source: <a href="https://gitlab.com/mrcinstefaniak/thing-tracker">https://gitlab.com/mrcinstefaniak/thing-tracker</a></p>
<p>Live sample: <a href="https://dashboard.heroku.com/apps/whispering-reef-13800">https://dashboard.heroku.com/apps/whispering-reef-13800</a></p>
<h2>Contact information</h2>
<p>E-mail: <a href="mailto:mrcinstefaniak@gmail.com">mrcinstefaniak@gmail.com</a></p>
<p>Gitlab: <a href="https://gitlab.com/mrcinstefaniak">https://gitlab.com/mrcinstefaniak</a></p>

app/views/page/help.html.erb
<h1>Help</h1>
<p>You can create account <%= link_to "here", new_user_path %>.</p>
<p>Then on you <%= link_to "account page", current_user %> or <%= link_to "home page", root_path %> you can create your new Tracker.</p>
<p>When you do this, click on the new Tracker's name and start posting your numbers!</p>

app/views/page/home.html.erb
<% if logged? %>
  <%= render partial: "trackers/new" %>
  <% current_user.trackers.each do |t| %>
      <% unless t.name.nil? %>
        <%= render partial: "trackers/tracker", locals: {t: t} %>
      <% end %>
  <% end %>
<% else %>
  <h1>Welcome to ThingTracker!</h1>
  <p>Would you like to note your numbers and display in graphs like that one?:</p>
  <%= render partial: "trackers/tracker", locals: {t: Tracker.find(1)} %>
  <p>With this app you can! Just create your account <%= link_to "here", new_user_path %>, and start tracking your things.</p>
  <p>If you require further help, please check this <%= link_to "link", 'page/help' %>.</p>
  <p>You can find all information to contact me <%= link_to "here", 'page/about' %>.</p>
<% end %>

app/views/trackers/_new.html.erb
<div class="tracker" style="border-color: lightgreen; padding: 10px;">
  <h1>New tracker</h1>
  <%= form_for @tracker_new do |f| %>
    <div class="form-row">
      <%= f.text_field :name, :placeholder => "Name" %>
    </div>
    <div class="form-row">
      <label class="form_field">
        Simple?
        <%= f.check_box :simple, class: "check" %>
      </label>
    </div>
    <div class="form-row">
      <%= select_tag "tracker[chart_type]", options_for_select([['Line', 1], ['Column', 2], ['Bar', 3], ['Area', 4]], 1) %>
    </div>
    <div class="form-row">
      <%= f.color_field :color, class: "btn" %>
    </div>
    <div>
      <%= f.submit "Create!", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/trackers/_tracker.html.erb
<div class="tracker" style="border-color: <%= t.color %>">
  <% u = User.find(t.user_id) %>
  <div class="tracker_title" style="border-color: <%= t.color %>">
    <% if logged? && current_user = t.user %>
      <div class="options">
        <%= link_to "delete", "/trackers/#{t.id}", method: :delete %>
      </div>
    <% end %>
    <a href="/trackers/<%= t.id %>">
    <%= t.name %>
    <div class="avatar small">
      <% if u.avatar.attached? %>
        <%= image_tag u.avatar %>
      <% end %>
    </div>
    <%= u.name %>
    </a>
  </div>
  <% if t.simple == 1 %>
    <% p = t.points.group_by_week(:created_at, last: 6).count %>
  <% else %>
    <% p = t.points.group(:created_at).sum(:value) %>
    <% if t.points.any? %>
      <% min = t.points.order(:value).limit(1).first.value*0.995 %>
      <% max = t.points.order(value: :desc).limit(1).first.value*1.005 %>
    <% end %>
  <% end %>
  <% if t.chart_type == 1 %>
    <%= line_chart p, colors: [t.color], min: min, max: max %>
  <% elsif t.chart_type == 2 %>
    <%= column_chart p, colors: [t.color], min: min, max: max %>
  <% elsif t.chart_type == 3 %>
    <%= bar_chart p, colors: [t.color] %>
  <% elsif t.chart_type == 4 %>
    <%= area_chart p, colors: [t.color], min: min, max: max %>
  <% end %>
</div>

app/views/trackers/show.html.erb
<%= render partial: "tracker", locals: {t: @tracker} %>
<% if logged? && current_user.id = @tracker.user_id %>
  <div class="tracker" style="border-color: <%= @tracker.color %>; padding: 10px">
    <div class="wrapper">
      <%= form_for :t, url: tracker_path, method: :patch do |f| %>
        <% if @tracker.simple == 0 %>
          <% p = @tracker.points.all %>
          <%= f.date_field :date, value: Date.current %>
          <%= f.number_field :points, step: 0.001, :placeholder => "Value" %>
          <%= f.submit "Save!", class: "btn" %>
        <% else %>
          <% 42.times do |p| %>
            <label class="simple-box">
              <div style="position: absolute"><%= Date.current - p %></div>
              <input type="radio" name="date" value="<%= Date.current - p %>" onclick="$('form').submit();" style="display: none">
              <% if @tracker.points.find_by(created_at: Date.current - p) %>
                <div class="yes"></div>
              <% else %>
                <div class="no"></div>
              <% end %>
            </label>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for  :user, url: user_path, method: :patch do |f| %>
  <% if params[:avatar] %>
    <div class="form-row">
      <%= f.file_field :avatar %>
    </div>
  <% end %>
  <% if params[:name] %>
    <div class="form-row">
      <%= f.text_field :name, :placeholder => "New name" %>
    </div>
  <% end %>
  <div class="form-row">
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>
  <div class="form-row">
    <%= f.submit "Save", class: "btn" %>
  </div>
<% end %>

app/views/users/index.html.erb
<% User.all.each do |u| %>
  <%= link_to u.name, u %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div class="form-row">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>
  <div class="form-row">
    <%= f.email_field :email, :placeholder => "E-mail" %>
  </div>
  <div class="form-row">
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>
  <div class="form-row">
    <%= f.password_field :password_confirmation, :placeholder => "Confirm password" %>
  </div>
  <div class="form-row">
    <%= f.submit "Create account!", class: "btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<a class="avatar" <% if logged? && current_user == @user %>href="<%= edit_user_path(:avatar => 1) %>"<% end %>>
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar %>
  <% end %>
</a>
<div>
  <a <% if logged? && current_user == @user %>href="<%= edit_user_path(:name => 1) %>"<% end %>><h1><%= @user.name %></h1></a>
</div>
<% if logged? && current_user == @user %>
  <%= render partial: "trackers/new" %>
<% end %>
<% @user.trackers.each do |t| %>
  <%= render partial: "trackers/tracker", locals: {t: t} %>
<% end %>